# frozen_string_literal: true

require 'date'

require 'apple_music/connection'
require 'apple_music/version'

module AppleMusic # :nodoc:
  autoload :Activity,               'apple_music/activity'
  autoload :Album,                  'apple_music/album'
  autoload :AlbumRelationship,      'apple_music/album_relationship'
  autoload :Artist,                 'apple_music/artist'
  autoload :ArtistRelationship,     'apple_music/artist_relationship'
  autoload :Artwork,                'apple_music/artwork'
  autoload :Chart,                  'apple_music/chart'
  autoload :Curator,                'apple_music/curator'
  autoload :CuratorRelationship,    'apple_music/curator_relationship'
  autoload :EditionalNotes,         'apple_music/editional_notes'
  autoload :Error,                  'apple_music/error'
  autoload :Genre,                  'apple_music/genre'
  autoload :GenreRelationship,      'apple_music/genre_relationship'
  autoload :History,                'apple_music/history'
  autoload :MusicGenre,             'apple_music/music_genre'
  autoload :MusicVideo,             'apple_music/music_video'
  autoload :MusicVideoRelationship, 'apple_music/music_video_relationship'
  autoload :PlayParameters,         'apple_music/play_parameters'
  autoload :Playlist,               'apple_music/playlist'
  autoload :PlaylistRelationship,   'apple_music/playlist_relationship'
  autoload :Preview,                'apple_music/preview'
  autoload :Rating,                 'apple_music/rating'
  autoload :Recommendation,         'apple_music/recommendation'
  autoload :Relationship,           'apple_music/relationship'
  autoload :Resource,               'apple_music/resource'
  autoload :ResponseRoot,           'apple_music/response_root'
  autoload :Search,                 'apple_music/search'
  autoload :Song,                   'apple_music/song'
  autoload :Station,                'apple_music/station'
  autoload :StationRelationship,    'apple_music/station_relationship'
  autoload :Track,                  'apple_music/track'
  autoload :TrackRelationship,      'apple_music/track_relationship'
  autoload :StoreFront,             'apple_music/store_front'
end
